### ISSUE TITLE
Can't locate Kernel/Output/HTML/TicketMenu/TeaserAttachmentView.pm

### ISSUE THREAD

**Issue by J0WI** [znuny/Znuny#12]
### Expected behavior

No regressions when updating to 6.0.32.

### Actual behavior

After Updating form OTRS Community to Znuny 6.0.32 the following error is shown:

```
Message: Can't locate Kernel/Output/HTML/TicketMenu/TeaserAttachmentView.pm in @INC (you may need to install the Kernel::Output::HTML::TicketMenu::TeaserAttachmentView module) (@INC contains: path/to/znuny/Custom path/to/znuny/Kernel/cpan-lib /path/to/znuny/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /etc/apache2) at path/to/znuny/bin/cgi-bin/../../Kernel/System/Main.pm line 85.
```

### How to reproduce

Opening a ticket.

### Environment

- OS: Debian 10
- Browser: n/a
- OTRS version: 6.0.32

**Comment by rkaldung** [comment]
Hi @J0WI,

The module TeaserAttachmentView is part of OTRS, former OTRS Business Solution, and not part of the Community Edition or Znuny. We removed these files because they do not have any functionality. I guess it was enabled on 

The command `bin/otrs.Console.pl Maint::Config::Rebuild --cleanup` executed with the OTRS user should help. It removes old system configuration settings which are not referenced in any of the XML files in Kernel/Config/Files/XML/

The module was responsible for this "advertisement":
![image](https://user-images.githubusercontent.com/378324/107707704-94c00700-6cc2-11eb-84a3-3285c0f2a5fc.png)

Let me know if this solution works for you.

**Comment by J0WI** [comment]
Great, thank you!
