### ISSUE TITLE
Bug - Keep login session connected on Safari

### ISSUE THREAD

**Issue by surak** [znuny/Znuny#148]
### Environment

- OS:           MacOS (multiple)
- Browser:      Safari (multiple)
- Znuny version: I don't see it - I can only see "znuny LTS"
### Expected behaviour

Once you login, that it would remember and stop asking for password every time

### Actual behaviour

The opposite: It keeps asking for login constantly.

### How to reproduce

1. Open a znuny ticket link
2. Safari will ask for login credentials.

### Additional information

This happens for as long as I remember.

**Comment by hanneshal** [comment]
Hi @surak,

we use Safari a lot and we cant confirm your issue. It is mostly related due to a misconfiguration. Either for the webserver or the Ticketing itself. 

Question: Do you have a session id in your url?

In the most cases Znuny is not able to create a cookie session when HTTP vs HTTPS and or the FQDN is mixed up. 
Check the config for:
- HTTPType
- FQDN 

and compare it to your real world values. They have to match. If you use ssl, HTTPType should https and vice versa. Also the FQDN has to match. 

Another possible case is that your IP is constantly changing. But this should be very unlikely. 
You can check for:
- SessionCheckRemoteIP
- SessionDeleteIfNotRemoteID
- SessionModule

Also please check the log. If you session module is FS, then there could also be an permission issue. 


Regards
Johannes

**Comment by surak** [comment]
Perfect! Will give it a try (means I'll bug the ticket sysadmins hehe). Thanks a lot!
