### ISSUE TITLE
[Solved] Issue - Tickets created by task: SpoolMailsReprocess, creating in invalid queue

### ISSUE THREAD

**Issue by Reedu** [znuny/Znuny#189]
### Environment

- OS:           Debian 10 
- Browser:      Firefox 95.0.2
- Znuny version: 6.2.2

### Expected behaviour

Reprocessed mails shoud be created in PostmasterDefaultQueue.

### Actual behaviour

Reprocessed mails are registering in queue.name = 'Postmaster' (i belive it fallback really to queue.id = 1)

### How to reproduce

1. Set different PostmasterDefaultQueue than Postmaster
2. Have some unprocessed emails
3. Run task
4. Check where're tickets created

### Additional information

Problem showed after update to 6.2.2 from 6.0.x.
Postmaster queue in our setup is disabled.

**Comment by hanneshal** [comment]
Hi @Reedu,

I don't think that this is quite correct. Let me explain, maybe we can find the solution to this:

The SpoolMailsReprocess command basically uses the PostMasterRead method. So all regular mechanisms are applied, as for regular E-Mails. This is also used if you process mails via .procmail (direct delivery) for example. 

[Spool](https://github.com/znuny/Znuny/blob/dev/Kernel/System/Console/Command/Maint/PostMaster/SpoolMailsReprocess.pm#L62)

The filter which handles the "queue decision", is this one. https://github.com/znuny/Znuny/blob/dev/Kernel/System/PostMaster/DestQueue.pm#L103

There may be more, but this one is related to the PostmasterDefaultQueueSetting. 

So mail is processed -> Parsed to the Postmaster process and (all) the filter start running. 
There is a comment right above L:103 which explains the handling

> If we get here means that none of the addresses in the message is defined as a system address
>  or an error occured while checking it.
Meaning: a mail sent to a not known system address or a mail which triggers filter errors, will be handled here.

Summary: 
If the sysconfig is set to a valid queue and the sysconfig is active, everything works as expected.  

If you try to invalidate a queue an error is shown:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/804939/149500775-7a60e9b9-c111-4d9a-8009-3ae6a4e7eeaf.png">

If the setting is invalid (due to manual editing/ earlier migrations / old configs) it may cause an unhandled behaviour and fallback to "1". But the the default setting, for example is not Postmaster, it is the Raw Queue. Postmaster often has ID 1, that is correct. 

But to be sure, you could post a screenshot of your Communication Log for this specific mails. Everything related to mail filter handling is logged there. Also in the time of reprocessing an info should be shown in the log. 

Both things would really help

Regards Johannes

**Comment by Reedu** [comment]
Result is built with this:
`        my $Result = system("$^X $Home/bin/otrs.Console.pl Maint::PostMaster::Read <  $File ");`

And in Read.pm we've got
`     my @Return = $PostMasterObject->Run(
            Queue => $Self->GetOption('target-queue'),
        );
`
otrs.Console.pl Maint::PostMaster::Read has parameter --target-queue which we didn't feed in SpoolMailsReprocess.pm 

I'm attaching screenshot of mail processed by Spool. It's only task that's is running everyday on 1:10.
My generic agents are not touching queue.
Postmaster queue has id=1 and is disabled in my config.

Communication log.
![MessageParseWithSpool](https://user-images.githubusercontent.com/41262899/149518353-bd4c676f-caae-4a97-9b31-b37ed0497297.png)

Ticket History (first article)
![HistoryTicket](https://user-images.githubusercontent.com/41262899/149518623-b077d0a8-5067-46a7-bf30-a4803fac7692.png)

**Comment by hanneshal** [comment]
We dont need the target-queue parameter here. 
Have a look at the communication log. The filter is running and gets a match.

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/804939/149518983-cac2c489-c537-4fbf-ab70-b764d622c451.png">

Please check the queue for the given system address. The filter gets a result for this address, which seems to be the postmaster queue.

**Comment by Reedu** [comment]
You're right. I thought that it should pick default queue, but it looks that i've more than one address and it's inproperly configured.
