### ISSUE TITLE
Feature request: Show and hide dynamic fields based on ticket / selected attributes. 

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#212]
I have complex activity dialogs where only some specific values ​​of individual fields lead to specific actions. If the combinations of values ​​and fields are not allowed, the dialog cannot be closed. This often irritates users.

In such cases it would be good if the fields of a dialog could be displayed dynamically. As a practical solution, I can suggest that the first field is always displayed. Depending on the values ​​selected by the user, either the second field or another field is displayed or not, and so on. This means that nonsensical combinations cannot be selected and the user feels guided through the complex query. After the last field fas filled/selected, the submit button changes from grey to colored to show the user he can proceed.

To achieve this, one could optionally introduce additional conditions for the display.
![image](https://user-images.githubusercontent.com/72391822/154218430-d1e148f9-b31b-47d3-8aac-b5ab31a5bf38.png)

These conditions should be tied to variables and specific values, e. g.:
![image](https://user-images.githubusercontent.com/72391822/154218745-43c2922b-7dc4-45d8-b854-9e051200ed60.png)

**Comment by schnudd31do3** [comment]
Supplement / Explanation: The dynamic view should be able to be made dependent on keys and / or values.

**Comment by hanneshal** [comment]
We already have this feature available, in different colours, as add ons. Based on templates, based on ticket attributes, based on permissions. We can cover basically every need. 
But: 
We wont implement them in the core at the moment due to the massive increase of complexity. 
Customers always go wild with the rules, once they have the opportunity and then loose track of it. 

Thats why we decided, for the moment, to not include this as a default feature. 

Regards

**Comment by schnudd31do3** [comment]
OK, thanks for your statement.
