### ISSUE TITLE
Bug - The search filter lists partially incorrect results

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#214]
### Environment
- Znuny version: 6.2.2

#######
![image](https://user-images.githubusercontent.com/72391822/154919086-86c8ce93-c688-425b-8874-0e03c7344532.png)
![image](https://user-images.githubusercontent.com/72391822/154919116-44fc04b6-c178-49e6-85ff-6aacabbe1e2e.png)

**Comment by hanneshal** [comment]
@schnudd31do3 Please use the issue template. It is there for a reason! 

**Question**: does your last Ticket contain an article with a matching sender? 
The "From Search" performs a lookup over the article table (Field: MIMEBase_From). So if your Ticket 4996000074 contains a article with a matching "FROM" sender, it works as designed.

**Comment by schnudd31do3** [comment]
It is as you suspected:
![image](https://user-images.githubusercontent.com/72391822/154935501-2d6ba8bc-7b83-4bd0-b840-7ca04b854ea8.png)
I would have expected that the creator of the ticket would not be changed when searching for "From". The email address doesn't match "Hartmut" either. It is the email address of the ticket creator "Dieter". If the "Sender" is already changed to "Hartmut", why his email address as well?

**Comment by hanneshal** [comment]
'From' is article related so are 'CC', 'BCC', 'Subject', 'Attachment name'
![image](https://user-images.githubusercontent.com/804939/154936814-87749f6e-3b71-412d-841e-d8655f4bf30e.png)

They don't have a relation to the Customer User / CustomerID, which are ticket attributes.

**Comment by schnudd31do3** [comment]
I understand. But how can I search for the creator of a ticket? I've tried the filter options that I judged to be the most likely to be successful. But the best result brought "From" with the described disadvantage.

**Comment by hanneshal** [comment]
We use GitHub for issues / bugs or feature requests. 

Please move your question to 
- The forum https://community.znuny.org (German area is available)
- Discord https://discord.gg/XTud3WWZTs (English preferred) 

Thanks

**Comment by schnudd31do3** [comment]
I have a feeling that reporting this bug is not being taken seriously by you. Why have you already closed the case when it's obviously a mistake? I only phrased it as a question because you described this behavior as normal, but it's not. If the display changes to "Hartmut", why isn't his email address updated under CustomerID, or if the CustomerID is "Dieter", why is the "Sender" changed? This is illogical from the user's point of view.

I just tested searching for CustomerID. It gaves me the same wrong result.

**Comment by hanneshal** [comment]
I closed this because it is my job to filter for user mistakes / questions and real bugs. 
We have made the decision from the start that we don't want to answer regular questions on GitHub and offer alternative ways to get free support. 

Back to your question:

You are searching for an article sender. The shown behaviour is no bug. > close the issue.
Now you switch context and start asking more question which are not related to your first question. 

CustomerID  | CustomerUser | Article Attributes are not related. 

1) A Ticket is created by an agent -> The agent selects the customer user. The Customer User ID is taken from the Customer User Database (AD, DB, Webservice...) 
2) A Ticket is created by E-Mail -> 
2.1) The user is known to the system -> The Customer User ID is taken from the Customer User Database (AD, DB, Webservice...) 
2.2) The user is not know to the system -> (Default is) The Customer User ID is the same as the sender E-Mail
3) A Ticket is created by Webservice -> same as 2.1 / 2.2

You can change the customer id any time. But it does not change anything related to the Article From.

I strongly believe you are just confused with the different wording. Which I can understand but I don't see a bug, but a general question. Where we have dedicated channels for. 

Because I don't understand this sentence:

> If the display changes to "Hartmut", why isn't his email address updated under CustomerID, or if the CustomerID is "Dieter", why is the "Sender" changed? This is illogical from the user's point of view.

Please clear things up: 
please describe the what you did exactly, with screenshots, maybe on a blank ticket and describe what you expect.

**Comment by schnudd31do3** [comment]
Thanks for waiting. In the meantime I found out that I encountered the behavior via the search function, but the problem does not come from the search function but is a general one. So I'm closing the bug.

**Comment by hanneshal** [comment]
Maybe we could discuss the new bug before you create it in the forum or using discord.

**Comment by schnudd31do3** [comment]
There is no longer a need for a new bug entry on this matter.
