### ISSUE TITLE
Breaking changes in Znuny patch level updates

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#244]
According https://semver.org/ patch level updates must not contain breaking changes.

In latest Znuny patch level updates one can see a few breaking changes, even schema changes(!):

02ac202c624bfccfd97e7f4ea95e0fd4adcf7a07
7436516bf5fb0d1cdad7e9028f0c601844185166

Breaking changes should not be introduced in patch level updates. If _absolutely_ necessary (i.e. serious security reasons), such breaking changes should not be introduced without release notes that _clearly_ point breaking changes and describe update steps required to be performed during this patch level update (similar as it was in OTRS CE times).

Application administrator should not be forced to dig into application sources/changelogs for discovering such surprises.

**Comment by hanneshal** [comment]
Hi @pboguslawski 

we had a long discussion about this. 
But your first commit is a security fix and is labeled as such. We wont leave those open in the field just because it may brake existing behaviour. So we had a choice to implement useless filters or go the way we have gone. 
Your solution to this kind of problem would be good to hear.

Number 2 - "Reset original owner on cancelling a bulk action", is in fact a bug which needed a fix cause it had major impact on several users of Znuny. 
I don't see why this is a breaking change for anyone. Yes we **add values to the schema** but we did not modify the columns or types. We just added a history type, to resolve this bug. 

Maybe you can explain why this is a breaking change for you, to help us get a better understanding for the next time. 

Regards
Johannes

**Comment by pboguslawski** [comment]
> Your solution to this kind of problem would be good to hear.

Any new release should be introduced with release notes (newsletter maybe like in OTRS CE times? another file/subdir with release notes in sources?) with clearly pointed breaking changes and update procedure if required (in this change even "warning: all your external commands in generic agent and ... will stop working after this update"  message will be better than nothing). Release notes should be understandable for admins without dev skills.

Another idea: teach Znuny sys admins to run some cmd on every update (even patch level) and detect there possible problems and generate warnings/apply required updates after confirmation (similar to update script in major version upgrades).

> Maybe you can explain why this is a breaking change for you

Because if administrator sees patch level update without any release notes and applies it without digging into source code (which should not be necessary), there won't be changes it their db, that should be there after update according to your schema subdir. Such initial content should be treated as part of "schema" if required to exits in db for Znuny to work fine.

**Comment by hanneshal** [comment]
Hi @pboguslawski 

ok. I understand your point 1 - we had this feedback on other channels to and we will make use of the community newsletter for this. We always point for those kind of information to the znuny.org page. 
https://www.znuny.org/en/releases/znuny-lts-6-0-41
But this does not seem to be enough. 
So we will push future releases to the Community Newsletter and I pass the information to the devs, add the link to the changes.md, if larger changes are needed. 


> > Maybe you can explain why this is a breaking change for you
> 
> Because if administrator sees patch level update without any release notes and applies it without digging into source code (which should not be necessary), there won't be changes it their db, that should be there after update according to your schema subdir. Such initial content should be treated as part of "schema" if required to exits in db for Znuny to work fine.

I still don't see why this is breaking. If you use the update script, the change is performed. And this is mandatory since version 6.0. 
And to be more clear: an INSERT is no schema change in any way. 

Regards
Johannes

**Comment by pboguslawski** [comment]
> We always point for those kind of information to the znuny.org page.

So there is release notes already; consider also sending it using newsletter for future releases.

> If you use the update script, the change is performed. And this is mandatory since version 6.0.

Can you please point to the Znuny docs mentioning what update command should be executed on every Znuny patch level update? Commit 7436516bf5fb0d1cdad7e9028f0c601844185166 updates only v6 upgrade script (and this change should be applied probably also for systems already upgraded to v6).

**Comment by hanneshal** [comment]
Hi @pboguslawski ,
> > We always point for those kind of information to the znuny.org page.
> 
> So there is release notes already; consider also sending it using newsletter for future releases.
> 
Thats what my last comment should say. We have this on the list for the next release. 
So it will happen on the next Release.

> > If you use the update script, the change is performed. And this is mandatory since version 6.0.
> 
> Can you please point to the Znuny docs mentioning what update command should be executed on every Znuny patch level update? Commit [7436516](https://github.com/znuny/Znuny/commit/7436516bf5fb0d1cdad7e9028f0c601844185166) updates only v6 upgrade script (and this change should be applied probably also for systems already upgraded to v6).

It is mandatory since 6.0, since "OTRS" Times. This is not a Znuny specific change.

<img width="1991" alt="image" src="https://user-images.githubusercontent.com/804939/167426652-dcf02ee9-4a62-4f14-90da-cbdfa546ecc3.png">
See Step 4 in the updating section:
https://doc.znuny.org/doc/manual/admin/6.0/en/html/updating.html

Regards

**Comment by pboguslawski** [comment]
> So it will happen on the next Release.

Thank you.

> It is mandatory since 6.0, since "OTRS" Times.

So 7436516bf5fb0d1cdad7e9028f0c601844185166 is not breaking. Thank you for explanation!

All explained so closing this issue.

**Comment by pboguslawski** [comment]
Please consider sending security advisories like

https://www.znuny.org/en/advisories/zsa-2021-04

via e-mail also for subscribers.

Thank you,

**Comment by hanneshal** [comment]
Hi @pboguslawski,

this is a service for payed support subscriptions. 
There is a RSS Feed and there will be a delayed release notification for the community in the future. As mentioned already.
