### ISSUE TITLE
Bug - DynamicFields are not working the subject of "Ticket escalation notification"

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#253]
### Environment

- OS:           Linux
- Browser:      Chrome
- Znuny version: 6.3.3.22.139

### Expected behaviour

The tag <OTRS_TICKET_DynamicField_XYZ> should work in the Subject of "Ticket escalation notification"

### Actual behaviour

It does not output the value of <OTRS_TICKET_DynamicField_XYZ> in the "Ticket escalation notification", **but it does it in e. g. "Ticket owner update notification"**. I could not completely test if all other ticket-notifications are OK.

This dynamic-field variable also is working OK in e. g. the subject of all auto-responses.

### How to reproduce
![image](https://user-images.githubusercontent.com/72391822/171654135-4cdcd9de-5ca1-4a35-8685-e5580b432994.png)

In the postmaster filter the dynamic-field variabme was set,
![image](https://user-images.githubusercontent.com/72391822/171656169-6fabc960-d5af-40a6-8c02-52dc8e930055.png)
( I guess, it doesn't matter where it was set)

**Comment by hanneshal** [comment]
Hi @schnudd31do3 

two questions:
1) Can you post the ticket history for this also please. 
2) What type is your DynamicField (Text, Dropdown....)

Thanks

**Comment by schnudd31do3** [comment]
There are is a lot of internal information in the history. I am not sure if it is a goot thing to post it here. Perhaps you could tel me items I should searching for.

The DynamicField is a text-type

**Comment by hanneshal** [comment]
Ok. I thought from your version number you are using a nightly build. My bad.

I tested the behaviour on the latest stable and it works as expected. 
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/804939/171666723-e30b5a05-207e-41a3-9e18-0365001caa46.png">

Ticket history:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/804939/171666442-85bcf1d2-d320-41b9-a56e-76a7bd0aa570.png">


DF Config:
<img width="1940" alt="image" src="https://user-images.githubusercontent.com/804939/171666566-1cbc6b60-345d-48cb-8b4d-616cf12a1c91.png">

Notification:
[Export_Notification_Ticket_escalation_notification.txt](https://github.com/znuny/Znuny/files/8825344/Export_Notification_Ticket_escalation_notification.txt)

I would need the DF Values and timestamps around the time when the escalation notification is send. 


Question: What does the subject show instead of the tag? 
Nothing or "-" ?

**Comment by schnudd31do3** [comment]
The notification was sent on 02-06-2022. The history on this day is:
![image](https://user-images.githubusercontent.com/72391822/171788725-b3e96cfa-72ef-4929-b347-f0e9f2b46aef.png)

This is the subject of the escalation notification:
![image](https://user-images.githubusercontent.com/72391822/171789864-ee25b394-ef9d-4f3c-9736-93586d07f2d1.png)

In the ticket owner update notification it works:
![image](https://user-images.githubusercontent.com/72391822/171789629-60c5d345-b551-4bde-978d-daa649becafc.png)

**Comment by hanneshal** [comment]
What I can tell from your screenshots is that the field is replaced. 
Otherwise: a) the tag would still be there b) there would be a "-" in the subject. 
Both is not the case. 

I can't get much out of the excerpt of your history. I need more details and I would suggest to create a dedicated test ticket.
I can also say, that the mechanism is the same for every notification. They are all handled by the same TemplateGenerator.

**Comment by schnudd31do3** [comment]
I made a testing ticket as adviced. I will keep you informed.

**Comment by schnudd31do3** [comment]
I think you are right: "What I can tell from your screenshots is that the field is replaced."

For some reasons I did not get any messages from my testing ticket, I have to investigate why.
But in the meantime I got further escalation notifications from other tickets with the same missing DF content.
Is there a way to debug? I did not find indications neither in the apache2's logs nor in the /opt/otrs/var/log/Daemon logs.

**Comment by hanneshal** [comment]
Hi,

no not really. I don't think that this is a code error. Thats the reason you probably won't find anything in the logs. 
You can only start debugging in the depth of the code to get to the root of this.

I think it is an issue with the template you are using or with the chain of events (field not filled at the time of sending).  Over the weekend I tried to recreate this, but it works good so far as I can tell. I even tried to it using PostmasterFilter (New and FollowUp). 

Are you sure that there is a value in the ticket at the time the escalation is sent?

**Comment by schnudd31do3** [comment]
I used the unchanged original body of the template and only modified the subject. After rewriting the subject with the same parameters, my testing ticket throwed an escalation message whith a subject as espected.
