### ISSUE TITLE
URL encounter OTRSAgentInterface problem

### ISSUE THREAD

**Issue by heikafeiylt** [znuny/Znuny#35]
Environment:
centos 7 
Apache 2.4.6
Znuny 6.033

一、Problem:
1、	The OTRSAgentInterface parameter appears when link to URI address

http://192.168.0.217/index.pl?OTRSAgentInterface=Z0rQNDl4EKYDu0cuU1Dh7ePhWXwdrlKH，
This makes it impossible for me to create a same page (a CTI function) to create a ticket, because the OTRSAgentInterface characters are random, and I have to login again every time to  find the similarities. 
2、	Click System Management-System Configuration,  when you change any parameter and deploy, the login address will pop up. I think this maybe also related to the appearance of OTRSAgentInterface.

二、Operation process
 
   As we know, the login address of zunny: http://ip/otrs/index.pl is a bit too long, and I hope to visit http://IP/index.pl directly, so I found the following post。
   https://forums.otterhub.org/viewtopic.php?f=60&t=9329
   The OTRSAgentInterface appear again when we change it.

1、I have ever tried to change the http://ip/otrs/index.pl to be http://ip/itsm/index.pl , OTRSAgentInterface will not appear in this case, suppose it maybe the problem of OTRS character.

Please refer the source code as below:
```
ScriptAlias /itsm/ "/opt/otrs/bin/cgi-bin/"

<Directory "/opt/otrs/bin/cgi-bin/">
    AllowOverride None
    Options +ExecCGI -Includes
    Order allow,deny
    Allow from all
    #
    # Below is what we copied from the <Location> section
    #  
    ErrorDocument 403 itsm/index.pl
    #  DirectoryIndex itsm/index.pl
    AddHandler  perl-script index.pl .cgi     <----- change ScriptHandler setting here.
    PerlResponseHandler ModPerl::Registry
    PerlOptions +ParseHeaders
    PerlOptions +SetupEnv
</Directory>
```

**Comment by eyazi** [comment]
I'd agree that the removal of "otrs/" in the URL is overdue (UX improvement), but your issue sounds like a misconfigured web server/Znuny. Get sure to keep the setting ScriptAlias empty if you remove the "otrs/".

**Comment by hanneshal** [comment]
Your first problem is related to your FQDN / SSL Config. 
1) There is a mismatch in the FQDN and the HTTP Type. So the system is not able to set a (secure) cookie and a fallback is called where the old URL Session is used. Fix the FQDN and SSL and the URL Session will disappear.

2) Is related to 1

3) Please move this question to the community forum. This is only a Apache related question. 
You have to change several configs in OTRS if you want to deliver it directly
Sysconfig:
- ScriptAlias
- (Frontend::WebPath) *optional if you modify the config also
Apache:
Script Alias needs to be modified https://github.com/znuny/Znuny/blob/rel-6_0/scripts/apache2-httpd.include.conf#L5
and the directory (Location)



A side note: 
We have issue / bug templates for a reason. If you have to delete the template because it does not fit your needs, it is questionable if this is the correct place to ask 😏
