### ISSUE TITLE
Visibility Improvement -Alert Notice Background Color

### ISSUE THREAD

**Issue by mo-azfar** [znuny/Znuny#449]
### Environment

- OS:           Windows
- Browser:      Edge
- Znuny version: 7.0.6

### Expected behaviour

More visibility (background color) on alert notice.

### Actual behaviour

Background color of alert notice is more like white. 

### How to reproduce

1. Go to 'Admin > System Configuration' (Should be the same with other that display alert notice)
2. Update any configuration
3. Alert notice appear on top with almost white background. Almost missing the alert notice sometime.

### Screenshots

![1](https://github.com/znuny/Znuny/assets/62957738/6415bb9a-f951-473c-8570-7c7393ee496a)

Should be better with another color ?

![2](https://github.com/znuny/Znuny/assets/62957738/d528d291-3888-4010-953c-67e37d07eafd)

**Comment by rkaldung** [comment]
@mo-azfar We will take are of this. Some discussion is required on what exactly to change.

**Comment by dignin** [comment]
Hi @mo-azfar and thanks for you report. This was part of the redesign. Using var/httpd/htdocs/skins/Agent/default/css/Core.Color.css it is possible to change these blocks to configure your colors.

```
    /* Alert Component */
    --alert-close-icon-color: var(--gray-dark);

        /* Info */
        --alert-info-bg-color: #50b6ff10;
        --alert-info-icon-color: #50B5FF;
        --alert-info-border-color: #50b6ff1a;

        /* Error */
        --alert-error-bg-solid-color: #FC5A5A;
        --alert-error-bg-color: #FC5A5A10;
        --alert-error-icon-color: #FC5A5A;
        --alert-error-border-color:#FC5A5A1a;

        /* Success */
        --alert-success-bg-solid-color: #3DD598;
        --alert-success-bg-color: #3DD59810;
        --alert-success-icon-color: #3DD598;
        --alert-success-border-color: #3DD5981a;

        /* Warning */
        --alert-warning-bg-color: #F2BD0E10;
        --alert-warning-icon-color: #F2BD0E;
        --alert-warning-border-color: #F2BD0E1a;

        /* Notice */
        --alert-notice-bg-color: #cccccc10;
        --alert-notice-icon-color: #cccccc;
        --alert-notice-border-color: #cccccc1a;

```

If you like, you can create your own [skin](https://doc.znuny.org/znuny_lts/developer/general_information/skins.html#skins) and [package](https://doc.znuny.org/znuny_lts/developer/extending/package-building.html#build-package) it.

I'm uncertain if we will change the defaults as it's easily configurable, but as this is not truly an "issue", I will close this issue. If you feel otherwise, please feel free to reopen the issue with your reasoning.
