### ISSUE TITLE
Bug - Snippets and Pictures/Smileys

### ISSUE THREAD

**Issue by BurtGummer** [znuny/Znuny#504]
Hello,

I try the Snippet-Function on Znuny 6.5.4 and have 2 problems:

![image](https://github.com/znuny/Znuny/assets/1249295/2615104f-31bb-4aa7-b58c-eee2e5cb9b4c)

1. If I enter smileys/emoji with WIN + . the smileys will not be saved. After saving there are the black ? symbols.
2. Same problem with a picture, If i save I get the error from the screenshot

**Comment by KaldungJr** [comment]
Hello, 

How large is the image file you tried to add to the snippet? What kind of database are you using for your system?

**Comment by BurtGummer** [comment]
Hello @KaldungJr,

the image has only some KB. We use Debian 11 with the Mariadb version 10.5.21. The thing is, we can use bigger pictures and smileys in the other text fields from znuny.

**Comment by KaldungJr** [comment]
Hello @BurtGummer, 

The reason emojis can't be saved is because the default database character set of Znuny does not support utf8mb4. As to the image not being saved, you said it was only a couple of KB which might be too large of an image file anyways since the default size for templates is 64 KB. 


Workaround: You can increase the column size with this SQL command `ALTER TABLE standard_template MODIFY COLUMN text MEDIUMTEXT;`

**Comment by rkaldung** [comment]
@BurtGummer Both issues are on our list, but the character set change won't come quickly. The column size is already addressed to development.

**Comment by rkaldung** [comment]
Internal Issue 773

**Comment by rkaldung** [comment]
Solved in Znuny LTS 6.5.5 with commit 901f10f3f1bfa1d96a43d122f6b4945d2e3c2ba7 and in Znuny 7.0.14 with 4f381e1689b174b64d2172373365ca62f04e70bb
