### ISSUE TITLE
Dashboard Reminder Tickets

### ISSUE THREAD

**Issue by saschaavt** [znuny/Znuny#522]
### Environment

- Server OS: Rocky Liux 8.9
- Browser: Edge
- Znuny version: 7.0.14
- 
### Expected behavior

The Reminder Tickets dashboard should show only tickets with a negative pending time

### Actual behavior

since upgrade to 7.0.14 the reminder dashboard shows ALL pending tickets. Even those with a pending time in the future

### How to reproduce

just go to the dashboard and look for the Reminder Tickets panel

### Screenshots

![grafik](https://github.com/znuny/Znuny/assets/96293205/217591f7-bb0e-42a9-b8da-954850cb69e5)

**Comment by dignin** [comment]
This change was intentional, and can be re-configured by you. The reason was, that pending tickets were otherwise not well visible on the dashboard, until expired. If you would like the previous behavior, edit the following setting.

```DashboardBackend###0100-TicketPendingReminder```

Set the Attributes key to:

TicketPendingTimeOlderMinutes=1;StateType=pending reminder;SortBy=PendingTime;OrderBy=Down;

![image](https://github.com/znuny/Znuny/assets/891283/b428047e-ed37-4180-81e1-2fb37ed25b7a)
