### ISSUE TITLE
Kernel::System::Web::UploadCache::DB problems with long filenames

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#78]
According to

https://github.com/znuny/Znuny/pull/77#issue-645204195

Kernel::System::Web::UploadCache::DB  needs fixing.

To fix it in simliar way as Kernel::System::Web::UploadCache::FS was fixed in PR above, DB schema need to be extended (new column for FilenameOrig required in web_upload_cache table).

Consider extending schema and fixing in upgrade to next major Znuny version 7.x.

**Comment by rkaldung** [comment]
I can confirm this as a bug and needs to be fixed. This is a entry from the application log:
```
[Tue Aug 31 16:57:23 2021][Error][Kernel::System::Web::UploadCache::DB::FormIDAddFile][107] Data too long for column 'filename' at row 1, SQL: '
            INSERT INTO web_upload_cache (form_id, filename, content_type, content_size, content,
                create_time_unix, content_id, disposition)
            VALUES  (?, ?, ?, ?, ?, ?, ?, ?)'
```

I attached a file with a name exceeding 250 character while adding a note. There was no error message in the UI and looks like this:
![image](https://user-images.githubusercontent.com/378324/131560950-7c660b64-335d-41e5-9301-e34d5ca47b98.png)

No size, no delete button. besides this you won't recognize there a problem because the note is properly added - just without the attachment.

I not sure if extending the database schema is a proper solution or implementing some kind of error message.

**Comment by jepf** [comment]
Internal issue: 291

**Comment by jepf** [comment]
This will be part of Znuny 6.5.1: 31e81f2a421d03e69a62c2afd75a3aec846f616f
