### ISSUE TITLE
Question - ITSM Addon releases for Znuny

### ISSUE THREAD

**Issue by tgurr** [znuny/Znuny#8]
I hope this is the right place to ask for this, previously OTRS offered the ITSM packages in the same version as the OTRS community edition and there were updates when a new OTRS version was released, else OTRS also complained in the Admin Interface that the versions don't match. How will this be handled for the Znuny version/fork?
* will there be updated ITSM releases as well to go in line with the Znuny releases?
* will the ITSM updates be available via the Znuny4OTRS "Addons - Znuny4OTRS / Public" repository for easy installation/update procedure like the OTRS ones were via the "OTRS::ITSM 6 Bundle Master" repository?
* if not, how should one proceed when having the ITSM Addon currently installed (and in use)?

**Comment by hanneshal** [comment]
Hello @tgurr 

yes we plan to update the ITSM packages. Currently we work on the test+build+package deploy chain. 
We are analysing parts of the code right now to see if there are big bugs to hunt or old scripts / dependencies to update. 

Feature wise we go the same path as with OTRS itself. If we release features, it will be in another branch, to keep the current one stable. We then will mark changes to the API, so that one can modify their code (addons), if needed. 

> else OTRS also complained in the Admin Interface that the versions don't match. How will this be handled for the Znuny version/fork

Where do you get this warning? I don't see one either in package manager nor in the support data collector.
Can you please provide a screenshot for this. 

Right now you can just install the full-ITSM package in version 6.0.30.
https://download.znuny.org/releases/itsm/bundle6/ITSM-6.0.30.opm

This works fine.

You can also add the path to your package manager, RepositoryList: https://download.znuny.org/releases/itsm/bundle6/
for the single packages: https://download.znuny.org/releases/itsm/packages6/
 
I'll forward your idea for an integration in the repo to the team. Would make things a bit easier, you are probably right.

Regards
Johannes

**Comment by tgurr** [comment]
Thanks for your detailed explanation and for forwarding the idea for an integration in the repo. I've now successfully migrated our OTRS 6.0.30 to Znuny 6.0.32.

> Where do you get this warning? I don't see one either in package manager nor in the support data collector.
Can you please provide a screenshot for this.

The warning you usually get after an upgrade to OTRS that some ITSM packages are not correctly installed and you should reinstall them.

![Screenshot_20210202_102850](https://user-images.githubusercontent.com/414984/106580285-01f4cf00-6542-11eb-8c89-c70fefacd15f.png)

![Screenshot_20210202_103537](https://user-images.githubusercontent.com/414984/106580977-a37c2080-6542-11eb-96ee-fc195cb7f51f.png)

I was under the impression that it's displayed because the versions don't match and to my experience they were always gone after upgrading the ITSM packages afterwards as well. But it turned out the messages are also gone after triggering a manual "reinstall" of the package in question OTRS complains about which seems to went through without any issues.

**Comment by rkaldung** [comment]
Hi @tgurr,

This warning is not related to the version of the ITSM packages. The core meaning of it:
> You have packages installed where files are not installed like expected.

The reason for this is pretty simple: some of ITSM packages modify original files of the framework. When the framework is updated these modifications are gone. You can fix this by reinstalling these addons. I recommend doing this via the shell as the otrs user:
```bash
otrs@host # bin/otrs.Console.pl Admin::Package::ReinstallAll
```
This command reinstalls all packages which claim not to be installed properly.

**Comment by tgurr** [comment]
@rkaldung thank you very much, thats calming to know and also thanks for the command line hint to make it even more convenient. Consider me a new happy user of Znuny for now, though I'm not yet sure where the journey leads to in the future after being offended by how OTRS has treated us community users with the sudden discontinuation of the community edition.
