### ISSUE TITLE
Support Data Collector shows warning about deprecated MySQL setting

### ISSUE THREAD

**Issue by arndkeyz** [znuny/Znuny#85]
### Environment

- OS:           Linux
- Browser:      Firefox
- Znuny version: 6.0.34

### Expected behaviour

No warning

### Actual behaviour

A warning is shown that the setting 'query_cache_size' should be used. 
This setting is deprecated as of MySQL 5.7.20 and is removed in MySQL 8.0.

### How to reproduce

1. Go to 'Admin'
2. Click on 'Support Data Collector'
3. Scroll down to 'Database'

### Additional information
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_query_cache_size

### Screenshots
![image](https://user-images.githubusercontent.com/41154642/119644197-e5e0aa80-be1c-11eb-83ab-878468bac005.png)

**Comment by hanneshal** [comment]
Thank you for the hint. It will be considered in the feature release mid 2021

**Comment by rkaldung** [comment]
- This setting is deprecated with MySQL 5.7.20 and removed in MySQL 8
- MariaDB states this setting is useful for "extremely useful in high-read, low-write environments". This is not typical for Znuny.

I recommend running MySQL with a disabled query cache. Builtin mechanisms of MySQL/MariaDB should be sufficient and other kinds of tuning are possible - if needed.

This issue can be solved by deleting `Kernel/System/SupportDataCollector/Plugin/Database/mysql/Performance.pm`.

@hanneshal I suggest this for 6.1.2 and 6.0.37 since it does not 'hurt'.

**Comment by rkaldung** [comment]
This was fixed with Znuny LTS 6.0.37 / Znuny 6.1.2
